networks:
  proxy:
    external: true
  internal:
    driver: bridge
    internal: true

services:
  remnawave-database:
    container_name: remnawave-database
    image: postgres:17.7
    restart: unless-stopped
    volumes:
      - /mnt/docker-volumes/remnawave:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=UTC
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 3s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true

  remnawave:
    container_name: remnawave
    image: remnawave/backend:2.6.4
    restart: unless-stopped
    depends_on:
      remnawave-database:
        condition: service_healthy
      remnawave-redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=remnawave-redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:postgres@remnawave-database:5432/postgres
      - IS_TELEGRAM_NOTIFICATIONS_ENABLED=false
      - METRICS_USER=admin
      - METRICS_PASS=admin
      - FRONT_END_DOMAIN=${DOMAIN}
      - SUB_PUBLIC_DOMAIN=${SUBSCRIPTION_SUBDOMAIN}.${DOMAIN}/${SUBSCRIPTION_PREFIX}
      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_API_TOKENS_SECRET=${JWT_API_TOKENS_SECRET}
    networks:
      - proxy
      - internal
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remnawave.rule=Host(`${REMNAWAVE_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.remnawave.middlewares=local-only@file"
      - "traefik.http.services.remnawave.loadbalancer.server.port=3000"
      - "traefik.http.routers.remnawave.tls.certResolver=letsencrypt"
      - "traefik.http.routers.remnawave.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.remnawave.tls.domains[0].sans=*.${DOMAIN}"
    security_opt:
      - no-new-privileges:true

  remnawave-redis:
    container_name: remnawave-redis
    image: valkey/valkey:8.1.5-alpine
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 3s
      timeout: 10s
      retries: 3
    command: |
      valkey-server --save "" --appendonly no --maxmemory-policy noeviction --loglevel warning
    security_opt:
      - no-new-privileges:true

  remnawave-subscription-page:
    container_name: remnawave-subscription-page
    image: remnawave/subscription-page:7.1.7
    restart: unless-stopped
    depends_on:
      remnawave:
        condition: service_healthy
    environment:
      - REMNAWAVE_PANEL_URL=http://remnawave:3000
      - REMNAWAVE_API_TOKEN=${REMNAWAVE_API_TOKEN}
      - CUSTOM_SUB_PREFIX=${SUBSCRIPTION_PREFIX}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remnawave-subscription-page.rule=Host(`${SUBSCRIPTION_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.services.remnawave-subscription-page.loadbalancer.server.port=3010"
      - "traefik.http.routers.remnawave-subscription-page.tls.certResolver=letsencrypt"
      - "traefik.http.routers.remnawave-subscription-page.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.remnawave-subscription-page.tls.domains[0].sans=*.${DOMAIN}"
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true